### ISSUE TITLE
Place search not working on the web 

### ISSUE THREAD

**Issue by angwandi** [bazrafkan/google_place#14]
Places search and the overall package does not work on the web

**Comment by khuongdn16** [comment]
I also run into this issue.

**Comment by tomrozb** [comment]
@bazrafkan would be great to remove "web" tag from pub.dev. I also run into this issue, just wasted 2h to realize web is not supported :)

**Comment by LucaDillenburg** [comment]
Does somebody know why it's not supported? I really needed it for the web. Does any body know any other solution?

**Comment by sarbogast** [comment]
As a workaround, here is what I ended up doing.

- Instead of this package, I used [this one](https://pub.dev/packages/google_maps_webservice) that has less nullable fields in responses and also adds the ability to make requests through a proxy
- I used the best answer in [this SO post](https://stackoverflow.com/questions/47076743/cors-anywhere-herokuapp-com-not-working-503-what-else-can-i-try/47085173#47085173) to deploy cors-anywhere to my heroku account
- Then I used the baseUrl argument to go through the proxy on heroku:

```
    final places = new GoogleMapsPlaces(
        apiKey: googlePlacesApiKey,
        baseUrl: kIsWeb
            ? 'https://[heroku app name].herokuapp.com/https://maps.googleapis.com/maps/api'
            : null,
      );
```
Note that you shouldn't use https://cors-anywhere.herokuapp.com as a proxy because it is a test set up, not meant to be used in real applications. I suspect that's why this proxy gets a FormatException.

**Comment by bazrafkan** [comment]
Now supported web implementation in version 0.4.2

**Comment by abdulrehmank7** [comment]
Instead of using this plugin, I created a utility class for Google places auto complete : https://arkapp.medium.com/flutter-and-google-map-for-beginners-part-1-fdba4ab22148
