### ISSUE TITLE
Why can't I get the platform specific API keys to work?

### ISSUE THREAD

**Issue by frankyvij** [bazrafkan/google_place#20]
Hi, thanks for the package. I do not want to enable web credentials on my google cloud - and I can't get my platform-specific credentials to work.

Is there a limitation like that?

**Comment by frankyvij** [comment]
I do have bundle identifier restriction on my cloud console configuration, but isn't that how it supposed to be?

**Comment by ys-li** [comment]
Same here. It's an awesome package but maybe since this particular plugin is implemented with HTTP requests instead of the official SDKs, we cannot get platform specific restrictions to work. This is a pretty significant barrier for production apps as restriction of API keys is important for preventing unauthorised uses.

**Comment by eliezerp3** [comment]
Any update on this? It is a big security risk to not have API credentials locked to a specific bundle ID in production.

**Comment by acoutts** [comment]
Hi please try with my PR here: https://github.com/bazrafkan/google_place/pull/27

**Comment by bazrafkan** [comment]
please check on 0.4.1 version

**Comment by dalton5** [comment]
is it working for you? Because from my side I have the error. I know it works because I can show my google map in the app and it is in the same api key.

Place API key is enabled.

And I setup the headers as below.

The detail error: 

"{
   "error_message" : "This IP, site or mobile application is not authorized to use this API key. Request received from IP address xxxxxxxxx8, with empty referer",
   "predictions" : [],
   "status" : "REQUEST_DENIED"
}
"

**Comment by dalton5** [comment]
Sorry I fixed it. Be careful.

**Ensure to remove the colons ':' in the sha**
