### ISSUE TITLE
Web proxyUrl

### ISSUE THREAD

**Issue by mmhobi7** [bazrafkan/google_place#35]
I am having trouble with proxyUrl, even with the demo of proxyUrl: 'cors-anywhere.herokuapp.com') or cors.bridged.cc (from https://github.com/Rob--W/cors-anywhere/issues/301#issuecomment-870990778). Any help would be appreciated.

**Comment by jardon-u** [comment]
For those discovering the issue. Google place api does not accept other websites to serve google content. Seems that this is only possible if you use the "Google Maps JavaScript API V3" (the official api that is web only). Unfortunately google_place (the flutter package) does not support this.
The solution for now is to deploy your own CORS proxy that will request the google place API and modify the response header to allow displaying the content anywhere.There are public CORS proxies but they limit the traffic and can be unsafe.
If you are on Heroku, check @LucaDillenburg answer in this thread. 
If you are on GCP, just follow the instructions in https://github.com/taichunmin/gcf-cors-anywhere
Finally, depending on your CORS proxy api (if you use the GCP link above for example) you might need to use a patched version of google_place (the master branch does not allow some formats: egs my-proxy/cors?url=...). In this case add google_place like this to your puspec.yaml
 ```
 google_place:
    git:
      url: https://github.com/Desync-o-tron/google_place
      ref: feature-paths-in-proxyUrl
```

**Comment by LucaDillenburg** [comment]
@log02 I believe a better solution would be to use the native SDKs instead of http requests in flutter web. I haven't tested it yet, but I believe it would remove the need of a cors-anywhere server. I found a package that claims to do just that:  [flutter_google_places_sdk](https://pub.dev/packages/flutter_google_places_sdk).
However, if you intent to use this package, you could pay for either GCP or Heroku, as the free versions of these services probably don't provide enough enough instances, RAM and etc for production use.

**Comment by log02** [comment]
thanks @LucaDillenburg I will test flutter_google_places_sdk
